#!/bin/sh
if [ -z "${GIT_COMMITTER_DATE:-}" ]; then
  lastCommitDate="$(git log -n 1 --pretty=format:"%ai")"
  d="$(date -d "$lastCommitDate" --iso-8601=seconds)"
  nd=${d:0:11}"00:00:00"${d:19:24}
  GIT_COMMITTER_DATE="$nd" git commit --amend --date "$nd" --no-edit
  echo "Commit time has been reset to $nd"
fi