#!/bin/sh
if [ -z "${GIT_COMMITTER_DATE:-}" ]; then
  d="$(date --iso-8601=seconds)"
  nd=${d:0:11}"00:00:00"${d:19:24}
  GIT_COMMITTER_DATE="$nd" git commit --amend --date "$nd" --no-edit
  echo "Commit time has been reset to $nd"
fi